### ISSUE TITLE
Battle{n} -> Battle{m}으로 갈 경우 UI들이 전부 켜진 상태로 시작하는 버그

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#22]

**Comment by wonAdam** [comment]
![image](https://user-images.githubusercontent.com/50472273/133397967-6f9f78fd-3807-40c1-864d-21d87404ca9d.png)

재현 방법
- Main씬에서 시작하면 Canvas를 DontDestroyOnLoad로 옮깁니다.
- 그리고 Battle1으로 씬이동합니다.
- 그리고 Battle2로 씬이동하면 버그 재현가능

**Comment by wonAdam** [comment]
@solhwi

**Comment by solhwi** [comment]
- 확인했습니다 젠장 수정하겠습니다

**Comment by wonAdam** [comment]
@solhwi 수정했으면 Close해주세요

**Comment by solhwi** [comment]
bug fixed
