### ISSUE TITLE
UIMgr에 외부에서 요청하여 UI를 띄울 수 있는 인터페이스 구현

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#28]
Battle에서는 그저 TurnMgr의 State에 따라 event를 받으면 UI를 조작하지만 그래도 그거와 상관없이 UI를 외부에서 요청하여 띄울 수 있는 메서드를 파주세요.

**Comment by wonAdam** [comment]
이게 왜 필요하냐면 유닛이 피격됐을때 숫자 UI를 띄울 것인데 이를 위함이고, 앞으로도 종료창이나 옵션창등으로 필요한 기능

**Comment by wonAdam** [comment]
@solhwi

**Comment by wonAdam** [comment]
Battle씬 뿐만아니라 다른 씬에서도 가능해야합니다.

**Comment by wonAdam** [comment]
@solhwi 
- UIMgr에 필요한 인터페이스
1. 요청하여 특정 Panel을 띄울수있는 인터페이스
2. 요청하여 열려있는 특정 Panel의 레퍼런스를 주는 인터페이스

**Comment by solhwi** [comment]
우선 작업 완 ㅡ 버그 있으면 말씀주세요~

**Comment by wonAdam** [comment]
작업한 인터페이스를 사용하여 다른 코드들 수정했습니다.
고생했으요~ 혹시 버그있으면 또다른 이슈에서 진행합시다.
