### ISSUE TITLE
EventParam을 UI에는 사용하지 말기....

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#31]

**Comment by wonAdam** [comment]
현재 UI에 넣었던 EventParam을 그대로 Event에도 사용하는 중....
둘이 분리하세요... @solhwi

**Comment by solhwi** [comment]
Battle UI들은 대부분 Event Invoke하며 EventParam으로 UI에 인자를 넘깁니다 혹시 이 부분을 EventParam없이 수정이 가능한가요?

**Comment by wonAdam** [comment]
이건 편이의 문제가 아니라 의미의 문제라...
EventParam가 UI에 사용되면 EventInvoke에도 사용할 수 있어서 편하긴하지만...
마치 스크루드라이버로 코코넛까먹는 느낌이라...
필요한 부분만 UIParam -> EventParam으로 변환하는 메서드를 구현하면 되겠지요?

**Comment by wonAdam** [comment]
내일 아침에 체크한번만 더 해볼게요. 우선 뭐 된거같으니 close.
