### ISSUE TITLE
Monobehaviour에는 생성자를 사용하지말자...

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#33]
@solhwi 

이제 발견했네.. Monobehaviour는 Awake와 Start등의 Monobehaviour Lifecycle에 의지해야지 생성자에 의지하면 안됨. (참고 https://answers.unity.com/questions/862032/c-constructor-in-monobehaviour.html)

**Comment by wonAdam** [comment]
Battle_UI에서 발견했으니 아마 UI들중에 생성자를 사용해서 구현한거? 전부 수정바람

**Comment by solhwi** [comment]
수정 완료
