### ISSUE TITLE
UIMgr이 IPanel들을 제대로 해제안하는 버그

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#44]
![image](https://user-images.githubusercontent.com/50472273/135006655-8336b235-2aa6-412b-9999-066b2123836c.png)

IPanel에 SetPanel, UnsetPanel을 잘 만들어놓고... UIMgr은 SetActive...?

이래서 현재 공격이 여러 유닛에서 나가는 버그가 있습니다... 수정부탁드립니다.

**Comment by solhwi** [comment]
픽스 완료!
