### ISSUE TITLE
Event에 너무 의존하고 있는 TurnMgr <-> UIMgr 

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#45]
이제 직접 UIComponent를 끄고 킬수 있는 인터페이스가 구비되었으니 이제 Event 청산에 들어갑니다.
TurnMgr은 Event로 UI로 끄고 킬게 아니라 직접 GetUIComponent & SetPanel & UnsetPanel로 끄고 킵니다.

**Comment by wonAdam** [comment]
@solhwi 
지금 UIMgr의 BattleCanvas에 ItemPanel관련해서 Event들을 주석처리해놨는데, 그거 내가 해놓은거임!
UIMgr이 Event들에 Register하는 것을 차근차근 없앨예정

**Comment by solhwi** [comment]
오우! 예

**Comment by wonAdam** [comment]
BattleMgr <-> UIMgr 의 Event의존도 청산 완료
TurnMgr <-> UIMgr은 주말에

**Comment by wonAdam** [comment]
@solhwi 
마무리했음.
이제 BattleCanvas가 거의 아무것도 안하게 됐는데,
그에 따른 리팩토링을 해야될것같음
