### ISSUE TITLE
유닛 선택 팝업 위치 버그

### ISSUE THREAD

**Issue by wonAdam** [CodeMonkeys-Graduation/Graduation-Project#48]
![image](https://user-images.githubusercontent.com/50472273/135790392-5ad0b614-1799-4718-be08-676a9d7961a8.png)

@solhwi 
???
오른쪽으로 붙여주세요

**Comment by wonAdam** [comment]
그리고 팝업을 닫으면 스테이지 선택 Glow를 해제해주세요 @solhwi

**Comment by wonAdam** [comment]
팝업을 닫으면 유닛 선택상태를 전부 0으로 만들어주세요 @solhwi

**Comment by solhwi** [comment]
해결완료~
