### ISSUE TITLE
2021-10-10 회의

### ISSUE THREAD

**Issue by ghost** [CodeMonkeys-Graduation/Graduation-Project#49]
## 한 일
- 솔휘
1. 유닛선택씬 : 안된 부분 (팝업시 playerdata초기화 & 잔버그 수정) #19 
(네이밍 피드백: RuntimeInterSceneData)
2. 다이얼로그: 스토리 + 맵 + 유닛 배치완료 #9 
3. SummonPanel : #32 

- 동현
1. GameOver & GameWin : Panel Show 로직 완료 #47
애니메이션등 비주얼 개선예정
2. 데미지 숫자 UI #18  
체력바 구현 예정

**Comment by wonAdam** [comment]
## 할 일
- 솔휘
1. 다이얼로그 애니메이션 하고 다이얼로그 씬 마무리
2. 씬 로더 구현 (아마도 UIMgr랑 연관이 깊을듯)

- 동현
1. 데미지입을시 체력바 UI
2. GameOver & GameWin Panel에 애니메이션 추가
3. 적군 Plannning UI
